
collection_roulette = {
      1 : ['plushpepe', "durovscap", "minioscar", "", "", ""],
      2 : ["deskcalendar", "candycane", "swagbag", "jollychimp", "ionicdryer", "genielamp"],
      3 : ["stellarrocket", "gingercookie", "lightsword", "jollychimp", "diamondring", "swisswatch"],
      4 : ["deskcalendar", "lolpop", "inputkey", "diamondring", "signetring", "artisanbrick"],
      5 : ["stellarrocket", "inputkey", "tophat", "swisswatch", "genielamp", "heroichelmet"],
      6 : ["jollychimp", "crystalball", "vintagecigar", "bondedring", "artisanbrick", "preciouspeach"],
      7 : ["ionicdryer", "diamondring", "swisswatch", "mightyarm", "preciouspeach", "heartlocket"],
      8 : ["lowrider", "genielamp","minioscar", "preciouspeach", "durovscap", "plushpepe"],
      9: ["deskcalendar", "bdaycandle", "candycane", "swagbag", "snoopdogg", "jollychimp"]
}

models_roulette = {
      "plushpepe": {
            "Aqua plush": 1,
            "Barcelona": 3,
            "Bavaria": 96,
            "Prices": {
                  1: 50,
                  5: 25,
                  10: 12
            }
      },
      "durovscap": {},
      "minioscar": {},
      "deskcalendar": {
            1: {"weight":80, "models":["Barbie Day","Basic Blue","Beachy","Beet","Diary","Black Flip","Blank Page","Blossoms","Blue Sky","Celebration","Fire Path","Fresh Start","Gold Leaf"]},
            2: {"weight":15, "models":["August","Balloon Face","Checklist","February","Friday","Groundhog Day",'October','September']},
            3: {'weight': 4, "models": ['Burning Time', 'Deadline', 'Peach Week','Telegram','Tic Tac Toe']},
            4: {"weight": 1, 'models': ['Independence','Hodler','Fawkes Night']}
      },
      "candycane": {
            1: {"weight": 80, "models": ["Discount Honeycomb",'Malfoy',"Short Circuit","Toxic Treat",'Angelius','Argento','Cherry Charm','Demonius','Hologlow','Lazy Nap']},
            2: {"weight": 20, "models": ['Designer','Hex Pot','Masterpiece','Mythic Candy','Weasley','Goldium','Grinch','Oblina','Negativus']}
      },
      "swagbag": {
            1: {"weight": 80, "models": [
    "Cookie Dude",
    "Blind Bag",
    "Darkness",
    "Golden Nugs",
    "Leopard",
    "P.I.M.P.",
    "The Last Meal",
    "Doll Buttons",
    "Snoop S",
    "Stack Pack",
    "April 20th",
    "Aviators",
    "Baggy Bag",
    "Bulk Order",
    "Candy Shop",
    "Doggy Doggs",
    "Doggystyle",
    "Fish Hat",
    "Money Bag",
    "Muffins",
    "Platinum 8",
    "Shuffle",
    "Take It Easy",
    "Walk Of Fame",
    "West Toast",
    "Bark & Tag",
    "Crook To Cook",
    "Purple Smoke",
    "Rastafari",
    "Serious Dude",
    "Tag Bag",
    "Choco Doggs",
    "Choco Kush",
    "Dogg Treats",
    "Dogg's Loot",
    "Gin and Juice",
    "Gummies",
    "Hop Corn",
    "Lollipops",
    "Platinum Drip",
    "Smokefest",
    "Snoopcoins",
    "Spicy Onion",
    "Lemon Pepper"
]},
            2: {"weight": 20, "models": ['Cashback','Gin & Jewels','Happy Herbs','Missionary','Snoop Life','Boiling Hot']}
      },
      "jollychimp": {
            1: {"weight": 70, "models": [
    "Ape Puppet",
    "Silverback",
    "Abubu",
    "Bananas",
    "Belle Bang",
    "Cavegirl",
    "Caveman",
    "French Cafe",
    "Genie",
    "Hex Witch",
    "Knight",
    "Little Sister",
    "Monkey Mouse",
    "Retro Cartoon",
    "Shaman",
    "Alarm Ape",
    "Crystal",
    "Fool King",
    "Grayscale",
    "Hot Springs",
    "Howler",
    "Luminous",
    "Policeman",
    "Toddler",
    "Baby Kong",
    "Bellboy",
    "Clash Elixir",
    "Coco Lime",
    "Early Adopter",
    "Farm Girl",
    "Jungle Pop",
    "Patchwork",
    "Snow Yeti",
    "Tourist"
]},
            2: {"weight": 20, "models": ['Cherub','Count Macaqula','Ape Puppet','Busy Mom','Chimp Imp','Gravity Bangs','Jason','Robo Kong']},
            3: {"weight": 10, "models": ['Smash King','Olympia','Bank Robber']}
      },
      "ionicdryer": {},
      "genielamp": {
          1: {"weight": 80, "models": ['Blueprint','Bronze Dust','Copper Pot','Dark Silver','Jade Lantern','Lime Art','Moonlight','Red Devil','Red Sketch','Sunset Rays','Sunshine','Golden Flame','Persian Dawn','Sahara']},
          2: {"weight": 20, "models": ['Inflated','Blue Neon','Meowgical','Night`s Wish','Mystic Aura','White Sprite','Chrome']}
      },
    "heroichelmet": {
        1: {"weight": 90, "models":[
    "Maya Warrior",
    "Giraffe",
    "Ladybug",
    "Pale Guard",
    "Pancake",
    "Watermelon",
    "Aphrodite",
    "Bengal Tiger",
    "Centurion",
    "Chieftain",
    "Milk Legend",
    "Aegean Sea",
    "Athena",
    "Desert Camo"
]},
        2:{"weight": 10, "models":[
    "Unicorn",
    "Atlantis",
    "Blue Parrot",
    "Happy Frog",
    "Quackus",
    "Skeleton",
    "Gladiator",
    "Hard Hat",
    "Hippotigris",
    "Liberty"
]}
    },
      "stellarrocket": {
            1: {"weight": 70, "models": [
    "Alien Pizza",
    "Astro Peach",
    "Banana",
    "Cardboard",
    "Checkered",
    "Chrome",
    "Clever Bird",
    "Fireworks",
    "First Step",
    "Fishing Cat",
    "Flower Power",
    "Green Jelly",
    "Gunship",
    "Hornet",
    "Jet Bike",
    "Jewels",
    "Knowledge",
    "Laika",
    "Lava Lamp",
    "Little Journey",
    "Lollipop",
    "Malfunction",
    "Neon Fuel",
    "Pencil",
    "Pepelatz",
    "Planet Express",
    "Popsicle",
    "Rocket Plush",
    "Ruby Sparkle",
    "Silver Ride",
    "Sky Ghost",
    "Soap Bubbles",
    "Squirrel",
    "Submarine",
    "Unicorn",
    "Vintage Toy"
]},
            2: {"weight": 20, "models":['space bot','police box','nostromo','Normandy', 'mega death', 'doomsday','baby carrot']},
            3: {"weight": 10, "models": ['black wing']}
      },
      "gingercookie": {
          1: {"weight": 70, "models": [
    "Amaretto",
    "Bronze",
    "Le Biscuit",
    "Lebkuchen",
    "Shanker",
    "Silver",
    "Berry Button",
    "Candy Cane",
    "Coffee Break",
    "Crunched",
    "Ginger Geek",
    "Hazel Bezel",
    "Melonius",
    "Santa Claus",
    "Herb Garden",
    "Red Scarf",
    "Reel Cookie",
    "Bavarian",
    "Choco Swirl",
    "Dandy Candy",
    "Lil Ginger",
    "Mint Fringe",
    "Sweetheart",
    "Cooking...",
    "Bio Glow",
    "Brownie",
    "Choco Glazed",
    "Cocoa Powder",
    "Dark Almond",
    "Madagascar",
    "Pink Molasses",
    "Raspberry",
    "Red Velvet",
    "Royal Sundae",
    "Toblerone",
    "Unicorn",
    "Eskimo",
    "Matrix",
    "Faint Blush",
    "Frosty",
    "Glowberry",
    "Johnny Ash",
    "Marshmallow",
    "Opposite",
    "Template",
    "Waffle",
    "Banana Bread",
    "Cardamom",
    "Champagne",
    "Frozen Dough",
    "Gentleman",
    "Icing Sugar",
    "Moon Dust",
    "Periwinkle",
    "Bordeaux",
    "Candy Bar",
    "Cheesecake",
    "Cinnamon",
    "Ginger Grape",
    "Hulking",
    "Ice Latte",
    "Marzipan",
    "Mr. Biscuit",
    "Pistachio",
    "Rose Water",
    "Rubber Duck",
    "Snowman",
    "Strawberry",
    "Sunspot",
    "Toffee",
    "Truffle",
    "Vanilla"
]},
          2: {"weight": 20, "models":['Reel Cookie','Black Beard','Jolly Roger','Adam', 'Sprinkles', 'Beach Party', 'Sugar Star', 'Brand New']},
          3: {"weight": 10, "models":['Cooking...','Headless','Dracula','White Gold','Platinum']}
      },
      "lightsword": {
          1: {"weight":70, "models": [
    "Absinthe",
    "Fukushimmer",
    "Tsunami",
    "Cultist",
    "Enforcer",
    "Bananakin",
    "Stick",
    "Andromeda",
    "Bifrost",
    "Brand Name",
    "Comics",
    "Crystal Queen",
    "Double Time",
    "Duelist",
    "Gaslight",
    "Hoth Aurora",
    "Hyperdrive",
    "Jedi Princess",
    "Jet Fuel",
    "Lava Forge",
    "Lotus Saber",
    "Low Battery",
    "Nunchaku",
    "Police Droid",
    "Polygon",
    "Prismatic",
    "Quasar",
    "Refraction",
    "Sensei",
    "Super Saiyan",
    "Toy Blade",
    "Valhalla",
    "Windu"
]},
          2: {"weight": 29, 'models':['Dragonfire','Electric Force','Love Samurai','Phantom','Stargazer','The Tempest','Clown Wars','Brand Name']},
          3: {"weight": 1, 'models':['Steve','Darksaber','Fury of Kylo','Jedi Luke','Master Yoda','Might of Maul','The Skywalker']}
      },
      "diamondring": {
          1: {"weight": 90, "models":[
    "Steampunk",
    "Sunset",
    "Twilight",
    "Acid Green",
    "Arabian Night",
    "Barbie Gem",
    "Black Amber",
    "Black Velvet",
    "Bronze Heart",
    "Canary",
    "Champagne",
    "Color Chaos",
    "Copper Rose",
    "Dark Orchid",
    "Dorodango",
    "Dragon Eyes",
    "Elven Tears",
    "Emerald",
    "Flamingo",
    "Forest Lake",
    "Honeydew",
    "Hot Pink",
    "Miami Beach",
    "Mint Candy",
    "Neon Chrome",
    "Peridot",
    "Prismatic",
    "Red Light",
    "Red Wedding",
    "Scrapyard",
    "Sovereign",
    "Topaz",
    "Vintage Glam",
    "Water Lily"
]},
          2: {"weight": 10, "models":[
    "Royal Purple",
    "Sapphire",
    "Silver Smoke",
    "Silver Star",
    "Sketch",
    "Snake Eye",
    "Tesla",
    "Valentine",
    "Velvet Rose",
    "Vice City",
    "Whirlpool",
    "Eclipse",
    "Obsidian",
    "Ocean Agate",
    "Ocean Gem",
    "Orion",
    "Pink Diamond",
    "Pink Lover",
    "Red Velvet",
    "Doodle",
    "Fireball",
    "Firestorm",
    "Freehand",
    "Frostband",
    "Inferno",
    "Iron Feather",
    "Line Art",
    "Manhattan",
    "Blood Band",
    "Blood Orange",
    "Bloodstone",
    "Bubble Burst",
    "Cold Desire",
    "Cold Fusion",
    "Color Blocks",
    "Color Spray",
    "Couture"
]}
      },
      "swisswatch" : {
          1: {"weight": 100, "models": ['Cherry Time','DeLorean','Future Watch','Pink Cycle','Salvador','The Grid','Helicopter','Full Tint','Gameboy','Pip-Boy','Asteroid']}
      },
      "lolpop": {
          1: {"weight": 100, "models": [
    "Andromeda",
    "Angelina",
    "Bitter Lemon",
    "Blender",
    "Blood Ember",
    "Blood Sucker",
    "Blue Goo",
    "Blueberry Pie",
    "Bubblegum",
    "Cappuccino",
    "Caramel",
    "Celestia",
    "Cherry Berry",
    "Cherry Cola",
    "Cherry Milk",
    "Choco Mint",
    "Choco Pop",
    "Citrone",
    "Cobweb",
    "Comic Crunch",
    "Cookie Dip",
    "Cosmic Green",
    "Cotton Candy",
    "Crystal Comet",
    "Crystalline",
    "Cucumber",
    "Dark Delight",
    "Dark Portal",
    "Dark Sky",
    "Delusion",
    "Doodle Art",
    "Einstein",
    "Fire Vortex",
    "Glowstick",
    "Gobstopper",
    "Gold Star",
    "Golden Amber",
    "Grape Gin",
    "Heart Pop",
    "Hexed Helix",
    "Holidaze",
    "Hollywood",
    "Honey Bee",
    "Iced Latte",
    "Icicle",
    "Icy Touch",
    "Jinxed",
    "Jolly Roger",
    "Lagoon",
    "Lavender Ice",
    "Liquid Lime",
    "Love Bubbles",
    "Lychee Mint",
    "Magic Wand",
    "Mandarin Ice",
    "Mandarin",
    "Melon Spin",
    "Milkshake",
    "Milky Way",
    "Mint Lemon",
    "Mirage",
    "Mortal Sin",
    "Nostalgia",
    "Old Liqueur",
    "Orangery",
    "Pina Colada",
    "Pineapple",
    "Pink Foil",
    "Plastic Ice",
    "Plum Candy",
    "Portable Pop",
    "Prisma",
    "Pumpkin Latte",
    "Pumpkin",
    "Rainbow Dash",
    "Red Grape",
    "Red Shift",
    "Refresh",
    "Rising Star",
    "Romance",
    "Rose Wine",
    "Rosebud",
    "Sailor Moon",
    "Satellite",
    "Shock Wave",
    "Sick Leave",
    "Soap Bubbles",
    "Spearmint",
    "Spectrum",
    "Spicy Tequila",
    "Sugar Free",
    "Sunset Blue",
    "Sweet Yogurt",
    "Sweetheart",
    "Tsunami",
    "Vanilla Jam",
    "Vanilla Swirl",
    "Watermelon",
    "Wild Mango",
    "Wonka Berry"
]}
      },
      "inputkey": {
          1: {'weight': 80, "models": [
    "Astrobot",
    "Chill Key",
    "Coffee",
    "Countdown",
    "CtrI+Pi",
    "Doomsday",
    "Earth",
    "End Game",
    "Euro",
    "Hashtag",
    "Helipad",
    "Hot Grill",
    "Infinity",
    "LOL",
    "Magic 8 Ball",
    "Nom-Nom",
    "Parking Lot",
    "Phosphorus",
    "Play Button",
    "Raido Rune",
    "Red Dice",
    "Ronaldo",
    "Search Engine",
    "Swimming Pool",
    "Switch",
    "Underwood",
    "V For Vegan",
    "Volcano",
    "Woodland"
]},
          2: {"weight": 20, "models": [
    "Ban Hammer",
    "Black Hole",
    "Blockchain",
    "Champion",
    "Continue",
    "Creeper",
    "Gold Star",
    "Incredible",
    "Jackpot",
    "Joker",
    "Love Button",
    "Matrix",
    "Money Printer",
    "Ninja",
    "Press F",
    "Purrfect Key",
    "Quad Damage",
    "Scared Cat",
    "Snoop Dogg",
    "Telegram",
    "The King",
    "Typewriter",
    "Utya",
    "X-Ray",
    "Zombie"
]}
      },
      "signetring": {
          1: {"weight": 80, "models":['Christmas','Clubs','Mandarin','Sapphire','Spades','Black Opal','Blue Gold','Blued Steel','Little Star','Onyx Demon','Green Rose','Platinum','Rose Gold','White Gold']},
          2: {"weight": 20, 'models': ['Silverscreen','Star Platinum','Symbolic','Candy Cane','Chrome','Citrine','Diamonds','Emerald','Green Lantern','Hearts','Liberty','Sakura Gold','Titanium','Yin-Yang','Gold']}
      },
      "artisanbrick": {
          1: {'weight': 90, 'models':[
    "Art Nouveau",
    "Cheesecake",
    "Chessboard",
    "Chocolate",
    "Domino",
    "Emerald",
    "Escher's Cube",
    "Fashion Bag",
    "Foosball",
    "Ghost Trap",
    "Grand Piano",
    "Retro Player",
    "Safe Box",
    "Sandstone",
    "Sardines",
    "Silver",
    "Toxic Ooze",
    "WATCH ME",
    "VHS Tape",
    "Watermelon"
]},
          2: {"weight": 10, "models":[
    "Buzzy Bee",
    "Delicate Wash",
    "Fifth Element",
    "Harlequin",
    "Jewelry Box",
    "Luggage",
    "Mimic Chest",
    "Molten Core",
    "Nuclear Waste",
    "Oranges",
    "Pearl",
    "Poker Chips",
    "Switch",
    "TON Ledger",
    "Treasure"
]}
      },
      "tophat": {
          1: {"weight": 80, "models":[
    "Blake",
    "Burned Brass",
    "Charlie",
    "Clockwork",
    "Limoncello",
    "Lincoln",
    "Willy Wonka",
    "Alabaster",
    "Black Raven",
    "Bloodline",
    "Cardinal",
    "Dreamwave",
    "Grandmaster",
    "Graphite",
    "Maestro",
    "Maroon",
    "Purple Rain",
    "Spectrum",
    "Starlight",
    "Victorian Era",
    "White Windsor"
]},
          2: {"weight": 20, "models":[
    "Dairy Dandy",
    "Pink Bunny",
    "Steampunk",
    "Submarine",
    "Chronos",
    "Bull Baron",
    "Cranberry",
    "Elegance",
    "Huntsman",
    "Silver Glass",
    "Blood Veil",
    "Crosswalk",
    "Low Rider",
    "Scrooge"
]}
      },
      "magicpotion": {},
      "astralshard": {
          1: {"weight": 90, "models":['Emerald','Spinel','Tanzanite','Tourmaline']},
          2: {"weight": 10,'models': ['Arctite','Jurassic','Glowstone','True Opal','Citrine','Ruby Fuchsite']}
      },
      "mightyarm": {},
      "preciouspeach": {},
      "heartlocket": {},
      "lowrider":{},
      "snoopdogg": {
            1: {"weight": 80, "models": [
    "Horseman",
    "Label Lord",
    "Plastic Beach",
    "Red Fur Coat",
    "Afro Disco",
    "Backspin",
    "Black Gold",
    "Captain Mack",
    "Dapper Doggo",
    "Retro Vibe",
    "Barks A Locks",
    "Blonde",
    "Bollywood",
    "Bow Wizzle",
    "Chow Wow",
    "Chrome",
    "Cold Topaz",
    "Emerald",
    "Green Light",
    "King Ruby",
    "Old School",
    "Sapphire",
    "Silver",
    "Streetwise",
    "Woofee",
    "Y2K Skin",
    "Yap Yap",
    "Barks Lightyear",
    "Beanie",
    "Black Diamond",
    "Funky Homie",
    "Long Beach",
    "Olympics",
    "Purple Hoodie",
    "Shower Cap",
    "Team USA",
    "Chill Homie",
    "Club Dawg",
    "Double G",
    "Fish Hat",
    "Groove Pup",
    "Huggy Bear",
    "Iconic Dude",
    "Peach Mode",
    "Super Bowl"
]},
            2:{"weight": 20, "models": ['Doggfather','Goldizzle','King Snoop','Al Dogg','Doberman','Retro Vibe']}
      },
      "bdaycandle" : {1: {"weight": 100, "models": [
    "Anniversary",
    "Backyard",
    "Be Awesome!",
    "Best Wishes",
    "Black Ink",
    "Blue Caramel",
    "Bright Side",
    "Broadway",
    "Bronze Age",
    "Bubbly",
    "Candy Message",
    "Cheers",
    "Cherrific",
    "Choco Wax",
    "Citrus Candy",
    "Confetti",
    "Cotton Candy",
    "Crazy Frog",
    "Crunchy",
    "Donut Cream",
    "Dream Big",
    "Duck Attack",
    "Eggcellent",
    "Eternal Glow",
    "Festive Day",
    "Festive",
    "Final Boss",
    "Firecracker",
    "Forecast",
    "Forever Young",
    "Fresh Mint",
    "Glitch",
    "Glittery Day",
    "Golden Age",
    "Golden Hour",
    "Happy Flame",
    "Happy Meows",
    "Ice Crackle",
    "Icicle",
    "Icy Pink",
    "Jage Crystal",
    "Jelly Bubble",
    "Jelly Desert",
    "Juicy Ginger",
    "Kaboom!",
    "Lolipop",
    "Magic Powers",
    "Melted Butter",
    "Midnight",
    "Moon Wish",
    "Mouse Brunch",
    "Multicolor",
    "Neon Lights",
    "Neon Sign",
    "Old Cartoon",
    "On Fire",
    "Orange Mood",
    "Party Hard",
    "Pastel Spark",
    "Payday",
    "Peachy",
    "Pear Cocktail",
    "Pinky Dream",
    "Pixel Wish",
    "Poltergeist",
    "Pop Art",
    "Pop Tart",
    "Princess",
    "Purr Magic",
    "Rainbow",
    "Red Ribbon",
    "Rose Mint",
    "Shine Bright",
    "Shine On",
    "Shocker",
    "Silver Year",
    "Small Gifts",
    "Sparkler",
    "Spring Meadow",
    "Stardust",
    "Starry Night",
    "Stay Cool",
    "Steel Strong",
    "Sugar Party",
    "Summer Walk",
    "Superstar",
    "Sweet Glaze",
    "Tender Flame",
    "Tropic Dream",
    "Tropicana",
    "Twilight Beam",
    "Valentine",
    "Wait a Minute",
    "Warm Wick",
    "Wax Glow",
    "Wee Hours",
    "Wicked",
    "Winter Fun",
    "Winter Noon",
    "You Rock!"
]}}
}

collection_saper = {
      1 : ["stellarrocket", "gingercookie", "jollychimp", "diamondring", "minioscar"],
      2 : ["bunnymuffin","inputkey", "tophat", "genielamp", "artisanbrick"]
}


groups = {
    6: {
        1: {"symbol": 1, "models": None, "weight": 15},
        2: {"symbol": 1, "models": ['Chimpool', 'Golden Monkey', 'Liberation', 'Smash King', 'Tired Primate', 'Cherub','Count Macaqula', 'La Baboon', 'Olympia', 'Bank Robber', 'Chimp Imp', 'Gravity Bangs', 'Jason', 'Robo Kong'], "weight": 15},
        3: {"symbol": 1, "models": ['Chimpool', "Golden Monkey", 'Liberation', 'Smash King', 'Tired Primate', 'Cherub', 'La Baboon', 'Olympia', 'Bank Robber'], "weight": 10},
        4: {"symbol": 2, "models": None, "weight": 15},
        5: {"symbol": 2, "models": ['Broken Heart', 'Disco', 'Druid Circle', 'Femme Fatale', 'Honey Cake', 'Sanguine', 'The Lich King', 'The Seeker', 'Wednesday', 'Baller', 'Billiard', 'Daisy', 'Incubus', 'Original Sin', 'World Cup', 'Poor Kitty'], "weight": 10},
        6: {"symbol": 2, "models": ['Broken Heart', 'Disco', 'Femme Fatale', 'Honey Cake', 'Sanguine', 'The Lich King', 'The Seeker', 'Wednesday', 'Baller', 'Incubus', 'World Cup'], "weight": 10},
        7: {"symbol": 3, "models": None, "weight": 10},
        8: {"symbol": 3, "models": ['El Classico', 'Ice Cold', 'Saturn V', 'Short Fuse', 'Spectral Smoke', 'Super Swirls', 'The Shocker', 'Far Out', 'Jazz Cigarette', 'Oil Baron', 'Pink Plume', 'Psychonaut', 'Ashtray', 'Centurion', 'Dark Clouds', 'Rainbow Road', 'Silver Fox', 'The Gentleman', 'Thermal'], "weight": 7},
        9: {"symbol": 3, "models": ['El Classico', 'Ice Cold', 'Saturn V', 'Short Fuse', 'Spectral Smoke', 'Super Swirls', 'The Shocker', 'Far Out', 'Jazz Cigarette', 'Oil Baron', 'Pink Plume', 'Psychonaut', 'The Gentleman'], "weight": 2},
        10: {"symbol": 4, "models": None, "weight": 6},
    }
}
